#!/usr/bin/env python3

"""
alert.py

Reads confirmed canary tampering events from monitor.py
and sends security alerts.
"""

import argparse
import json
import time
import os
from datetime import datetime


# ---------------------------------------------------
# Configuration
# ---------------------------------------------------

parser = argparse.ArgumentParser(description="Canary tampering alert system")

parser.add_argument(
    "--event-log",
    default="events.jsonl",
    help="Path to events.jsonl generated by monitor.py"
)

args = parser.parse_args()

EVENT_LOG = args.event_log


# Keep track of events already alerted
seen_events = set()

# Keep track of where we stopped reading
last_position = 0


# ---------------------------------------------------
# Read new events
# ---------------------------------------------------

def load_new_events():
    """
    Reads only NEW tampering events from events.jsonl
    """

    global last_position

    if not os.path.exists(EVENT_LOG):
        return []

    events = []

    try:

        with open(EVENT_LOG, "r") as file:

            # Jump to where we stopped last time
            file.seek(last_position)

            for line in file:

                try:

                    event = json.loads(line)

                    event_id = (
                        event.get("timestamp"),
                        event.get("path")
                    )

                    if event_id not in seen_events:

                        seen_events.add(event_id)
                        events.append(event)

                except json.JSONDecodeError:
                    continue

            # Save current reading position
            last_position = file.tell()

    except OSError:
        pass

    return events


# ---------------------------------------------------
# Severity calculation
# ---------------------------------------------------

def calculate_severity(event):
    """
    Gives higher severity to suspicious activity
    """

    if event["action"] == "deleted":
        return "CRITICAL"

    if len(event.get("suspect_processes", [])) > 0:
        return "HIGH"

    if event["reason"] == "hash mismatch":
        return "MEDIUM"

    return "LOW"


# ---------------------------------------------------
# Send alert
# ---------------------------------------------------

def send_alert(event):

    severity = calculate_severity(event)

    print("\n" + "=" * 60)

    print("🚨 SECURITY ALERT 🚨")

    print("=" * 60)

    print(
        f"""
Severity:
{severity}

Time:
{event.get('timestamp')}

Affected File:
{event.get('path')}

Detection Reason:
{event.get('reason')}

Action:
{event.get('action')}

Suspected Process:
{event.get('suspect_processes')}
"""
    )

    print("=" * 60)

    save_alert_log(event, severity)


# ---------------------------------------------------
# Save history
# ---------------------------------------------------

def save_alert_log(event, severity):
    """
    Saves alert history
    """

    with open("alerts.log", "a") as file:

        file.write(
            f"""
[{datetime.now()}]

SECURITY ALERT

Severity:
{severity}

File:
{event.get('path')}

Reason:
{event.get('reason')}

Action:
{event.get('action')}

--------------------------------

"""
        )


# ---------------------------------------------------
# Main
# ---------------------------------------------------

def main():

    print("Monitoring ransomware events...")
    print(f"Reading events from: {EVENT_LOG}")

    while True:

        new_events = load_new_events()

        for event in new_events:

            send_alert(event)

        time.sleep(1)


if __name__ == "__main__":
    main()
